config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'static#dashboard'
  get 'people/:id', to: 'static#person'
  resources :expenses do
    collection do
      get :settle_up
      put :update_settle_expenses
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/expense_logic.rb
# frozen_string_literal: true

module ExpenseLogic
  extend ActiveSupport::Concern

  def distribute_expense(expense, user_ids, unequally_distributed_amounts, payee_id)
    if unequally_distributed_amounts.blank?
      distribute_evenly(expense, user_ids, payee_id)
    else
      distribute_unevenly(expense, unequally_distributed_amounts)
    end
  end

  def distribute_evenly(expense, user_ids, _payee_id)
    shared_amount = (expense.amount / user_ids.count).round(2)
    user_ids.each do |share_user_id|
      next if share_user_id.to_i == expense.paid_by_id

      expense.shared_expenses.create(amount: shared_amount, description: expense.description,
                                     share_user_id: share_user_id, paid_by_id: expense.paid_by_id)
    end
  end

  def distribute_unevenly(expense, unequally_amounts)
    unequally_amounts.each do |id, amount|
      next if id.to_i == expense.paid_by_id
      expense.shared_expenses.create(amount: amount, description: expense.description, share_user_id: id,
                                     paid_by_id: expense.paid_by_id)
    end
  end

  class_methods do
    def create_with_participants(expense_params, share_user_ids, shared_user_amounts, payee)
      user_ids = share_user_ids.reject(&:blank?)
      unequally_distributed_amounts = shared_user_amounts.to_unsafe_h.reject { |_key, value| value.blank? }
      ActiveRecord::Base.transaction do
        expense = payee.expenses.create!(expense_params)
        expense.distribute_expense(expense, user_ids, unequally_distributed_amounts, payee.id)
        payee.create_friends(share_user_ids, payee)
      rescue Exception => e  # Catch transaction rollback
        false
      end
    end

    def settle_expense(settle_param, curr_user)
      share_expenses = curr_user.shared_expenses.exclude_settled.where(paid_by_id: settle_param[:settle_to_id])
      settle_amout = share_expenses.sum(:amount)
      if settle_amout == settle_param[:amount].to_f
        curr_user.settle_expenses.create!(settle_param)
        share_expenses.update(amount: (settle_amout - settle_param[:amount].to_f))
      end if !settle_amout.zero?
    end
  end
end

app/models/expense.rb
# frozen_string_literal: true

class Expense < ApplicationRecord
  include ExpenseLogic
  attr_accessor :shared_user_ids
  attr_accessor :shared_user_amounts

  belongs_to :user
  belongs_to :paid_by, class_name: 'User', foreign_key: 'paid_by_id'
  has_many :shared_expenses, dependent: :destroy

  accepts_nested_attributes_for :shared_expenses

  validates :amount, :description, :paid_by, presence: true
  validates :amount, numericality: { greater_than: 0 }

  before_create do
    self.sub_total = amount
  end

  def self.expense(user)
    where(paid_by: user.id).pluck(:id)
  end
end

app/models/friend.rb
# frozen_string_literal: true

class Friend < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
  scope :get_user_friends, -> (user_id) { where(friend_id: user_id) }
  scope :get_already_created, -> (user_id, friend_id) { where(user_id: [user_id, friend_id], friend_id: [user_id, friend_id]) }

  validate :validate_friend

  private

  def validate_friend
    errors.add(:base, "Alreday created") if Friend.get_already_created(self.user_id, self.friend_id).present?
  end
end

app/models/settle_expense.rb
class SettleExpense < ApplicationRecord
  belongs_to :settle_by, class_name: :User, foreign_key: :settle_by_id

  validates :amount, presence: true
  validates :amount, numericality: { only_numeric: true }
end

app/models/shared_expense.rb
# frozen_string_literal: true

class SharedExpense < ApplicationRecord
  belongs_to :expense
  belongs_to :paid_by_user, class_name: :User, foreign_key: :paid_by_id
  belongs_to :share_by_user, class_name: :User, foreign_key: :share_user_id\

  scope :exclude_settled, -> {where.not(amount: 0)}

  def self.total_owed(current_user)
    where(expense_id: Expense.expense(current_user)).sum(:amount)
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :friends, dependent: :destroy
  has_many :expenses, dependent: :destroy
  has_many :paid_expenses, class_name: :SharedExpense, foreign_key: :paid_by_id, dependent: :destroy
  has_many :shared_expenses, class_name: :SharedExpense, foreign_key: :share_user_id, dependent: :destroy
  has_many :settle_expenses, class_name: :SettleExpense, foreign_key: :settle_by_id, dependent: :destroy

  def not_friends_with_me
    User.where.not(id: friend_ids << id)
  end

  def owed_expenses
    paid_expenses.sum(:amount).round(2)
  end

  def owe_expenses
    shared_expenses.sum(:amount).round(2)
  end

  def owe_user
    shared_expenses.joins(:paid_by_user).group( 'users.name', 'paid_by_id').sum(:amount).delete_if { |k,v| v.zero? }
  end

  def owed_user
    paid_expenses.joins(:share_by_user).group('users.name', 'share_user_id').sum(:amount).delete_if { |k,v| v.zero? }
  end

  def get_friend_ids
    friends.pluck(:friend_id)
  end

  def friend_ids
    get_friend_ids.concat(Friend.get_user_friends(id).pluck(:user_id))
  end

  def create_friends(friend_ids, curr_user)
    friend_ids = friend_ids.reject(&:blank?)
    friend_ids.each {|f_id| curr_user.friends.create(friend_id: f_id) if curr_user.id != f_id.to_i }
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/expenses_controller.rb
# frozen_string_literal: true

class ExpensesController < ApplicationController
  before_action :set_expense, except: [:create, :edit]
  def create
    expense = Expense.create_with_participants(expense_params, params['expense']['shared_user_ids'],
                                               params['shared_user_amounts'], current_user)
    if expense
      flash[:notice] = 'expense create successfully!'
    else
      flash[:alert] = "unable to create expense"
    end
    redirect_to root_path
  end

  def edit
    @expense = Expense.includes(shared_expenses: :share_by_user).find_by_id(params[:id])
  end

  def update
    render :edit unless @expense.update(expense_params)
  end

  def settle_up
    @you_are_owed_user = current_user.owe_user
  end

  def update_settle_expenses
    settle = Expense.settle_expense(settle_param, current_user)

    if settle
      flash[:notice] = 'Expense settled.'
    else
      flash[:alert] = "unable to perform"
    end
    redirect_to root_path
  end

  private

  def expense_params
    params.require(:expense).permit(:description, :amount, :paid_by_id, :tax, :tip, :sub_total, shared_expenses_attributes: [:id, :amount])
  end

  def settle_param
    params.permit(:settle_to_id, :amount, :additional_note)
  end

  def set_expense
    @expense = Expense.find_by_id(params[:id])
  end
end

app/controllers/static_controller.rb
# frozen_string_literal: true

class StaticController < ApplicationController
  before_action :get_friends, :expense

  def dashboard
    @you_owe_user = current_user.owe_user
    @you_are_owed_user = current_user.owed_user
  end

  def person
    @expenses = Expense.includes(:shared_expenses).where(user_id: params[:id])
  end

  private

  def get_friends
    @users = User.all
    @friends = User.where(id: current_user.friend_ids.uniq)
  end

  def expense
    @expense = Expense.new
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/expenses_helper.rb
# frozen_string_literal: true

module ExpensesHelper
end

app/helpers/friends_helper.rb
# frozen_string_literal: true

module FriendsHelper
end

app/helpers/static_helper.rb
# frozen_string_literal: true

module StaticHelper
end

app/views/expenses/_add_tax_modal.html.slim
- shared_expenses = @expense.shared_expenses
.modal-header
  h5.modal-title#editModalLabel itemized expense
  button.btn-close aria-label="Close" data-bs-dismiss="modal" type="button"
= form_with model: @expense, local: false do |f|
  .modal-body
    .container-fluid
      .row.fw-bold.flex-nowrap
        .col-4 Item
        .col-3.text-center $
        .col.overflow-auto
          .d-flex.justify-content-around
            - shared_expenses.each_with_index do |shared_expense, i|
              span.text-center style="font-size: 9px;" = shared_expense.share_by_user.name

      -# Row for shared user amount
      .row.flex-nowrap
        .col-4
          = f.text_field :description, class: 'form-control'
        .col-3
          = f.number_field :sub_total, class: 'form-control t-column-1', readonly: true
        .col.overflow-auto
          .d-flex.justify-content-around.align-items-center
            - shared_expenses.each_with_index do |shared_expense, i|
              span class="overflow-auto expense-amount t-column-#{i+2}" style= "width: 60px" = shared_expense.amount

      -# Subtotal Row
      .row.fw-bold.align-items-center.flex-nowrap style= "height: 50px"
        .col-4
          span Sub total
        .col-3.text-center
          span = @expense.amount
        .col.overflow-auto
          .d-flex.justify-content-around.align-items-center style= "height: 50px"
            - shared_expenses.each do |shared_expense|
              span.overflow-auto style= "width: 60px" = shared_expense.amount

      -# Tax fields row
      .row.flex-nowrap
        .col-4.fw-bold
          span + Tax
        .col-3
          = f.number_field :tax, class: 'form-control t-column-1', id: "taxAmount"
        .col.overflow-auto
          .d-flex.justify-content-around.align-items-center
            - shared_expenses.each_with_index do |shared_expense, i|
              span class="overflow-auto shared-tax-amount expense-amount t-column-#{i+2}" style= "width: 60px" 0.0

      -# Tip fields row
      .row.flex-nowrap style='margin-top: 10px;'
        .col-4.fw-bold
          span + Tip
        .col-3
          = f.number_field :tip, class: 'form-control t-column-1', id: "tipAmount"
        .col
          .d-flex.justify-content-around.align-items-center
            - shared_expenses.size.times do |i|
              span.overflow-auto class="shared-tip-amount expense-amount t-column-#{i+2}" style= "width: 60px" 0.0

      -# Total fields row
      .row.align-items-center.fw-bold.flex-nowrap style= "height: 50px"
        .col-4
          span Grand Total
        .col-3.text-center
          = f.text_field :amount, class: "form-control total-calculation border-0 fw-bold", id: "t-column-1", value: 0.0, readonly: true, style: 'background-color: white'
        .col.overflow-auto
          .d-flex.justify-content-around.align-items-center style= "height: 50px"
            - @expense.shared_expenses.each_with_index do |shared_expense, i|
              = f.hidden_field "shared_expenses_attributes[#{shared_expense.id}][id]", value: shared_expense.id
              = f.text_field "shared_expenses_attributes[#{shared_expense.id}][amount]", class: "form-control total-calculation border-0 fw-bold", id: "t-column-#{i+2}", value: 0.0, readonly: true, style: 'background-color: white'
  .modal-footer.justify-content-between
    div
      span.fw-bold Note:
      span  Your share amount is not listed here
    div
      button.btn.btn-success type="submit" Submit
      button.btn.btn-secondary aria-label="Close" data-bs-dismiss="modal" type="button" Close

app/views/expenses/_expense_form.html.slim
        - @friends_with_current_user = @users.to_a.map { |friend| [friend == current_user ? 'You' : friend.name, friend.id] }
        = simple_form_for @expense, url: expenses_path, html: { class: "ulsa-login-form", autocomplete: "off" } do |f|
          - if @expense.errors.any?
              .alert.alert-danger
                ul
                  - @expense.errors.full_messages.each do |message|
                    li= message
          .form-group.mb-3
            = f.input :paid_by_id, label: 'Paid By', collection: @friends_with_current_user, prompt: "Select User", input_html: { class: "form-control" }
          .form-group.mb-3
            label
              input#equallyCheckbox(type='checkbox' name='equallyCheckbox')
              | Equally
            label
              input#unequallyCheckbox(type='checkbox' name='unequallyCheckbox')
              | Unequally
          .equally-fields(style='display:none;')
            .form-group.mb-3
              = f.input :shared_user_ids, label: 'Share with', collection: @friends_with_current_user, input_html: { class: "form-control", multiple: true }
          .unequally-fields(style='display:none;')
            .form-group.mb-3
              = label_tag 'selected_friends', 'Share with:'
              .scrollable-checkbox-list
                .checkbox-list
                  - @friends_with_current_user.each do |friend|
                    label
                    = check_box_tag "shared_user_ids[]", friend.second, nil, class: 'friend-checkbox'
                    = friend.first
                    .friend-amount-input id="friend_amount_input_#{friend.second}" style="display: none;"
                      .form-group.mb-3
                        label= friend.first
                        = text_field_tag "shared_user_amounts[#{friend.second}]", nil, class: "form-control friend-amount", type: "number", placeholder: "Enter amount for #{friend.first}"

          .form-group.mb-3
            = f.input :amount, as: :string, label: 'Amount', input_html: { class: "form-control" }
          .form-group.mb-3
            = f.input :description, as: :text, label: 'Description', input_html: { class: "form-control"}
          .form-group.mb-3
            = f.submit 'Save changes', class: 'btn btn-primary', id: 'saveButton'

app/views/expenses/_settle_up.html.slim
= form_tag update_settle_expenses_expenses_path, method: :put do
  .modal-header
    h5#expenseModalLabel.modal-title Settle up
    button.btn-close aria-label="Close" data-bs-dismiss="modal" type="button"
  .modal-body
    .participants
      .participant
        = image_tag "https://cdn.icon-icons.com/icons2/1378/PNG/512/avatardefault_92824.png", alt: "profile", class: "participant-avatar"
        .arrow-icon
          = image_tag asset_path("arrow_right_icon_238984.png"), alt: "profile", class: "arrow"
        = image_tag "https://cdn.icon-icons.com/icons2/1378/PNG/512/avatardefault_92824.png", alt: "profile", class: "participant-avatar"
        #display_user_name.participant-labels
      .participant-labels
        p
          | You &nbsp&nbsp&nbsp&nbsp&nbsp Paid
    .select-to-settle
      = select_tag "settle_to_id", options_for_select(@you_are_owed_user.collect{ |user, amount| user.unshift("#{user[0]} (Settle Amount: #{amount})") }), include_blank: "Select User", class: "settle-select"
    .amount-to-pay
      = text_field_tag 'amount', nil, placeholder: "Amount", id: 'settle-amount'
    .date-field
      = date_field_tag(:datetime_ida, Date.today, class: "date-picker")
    .optional-note
      = text_area_tag 'additional_note', nil, placeholder: "Additional Note", class: "note-textarea"
  .modal-footer
    .form-actions
      = submit_tag "Save", class: 'btn btn-primary'
      = button_tag 'Close', class: 'btn btn-secondary', type: 'button', data: { bs_dismiss: 'modal' }

app/views/expenses/edit.js.erb
subTotal = <%= @expense.amount%>
shareUserCount = <%= share_user_count = @expense.shared_expenses.count + 1%>
sharedTax = <%= (@expense.tax / share_user_count).round(2) %>
sharedTip = <%= (@expense.tip / share_user_count).round(2) %>

html = '<%= render 'add_tax_modal' %>';

$('#add-tax-modal .modal-content').html(html);
$('.shared-tax-amount').text(sharedTax);
$('.shared-tip-amount').text(sharedTip);

calculateTotals = () => {
  $('.total-calculation').each((index, totalRowEl) => {
    column = totalRowEl.id;
    total = 0;
    $('.' + column).each((index, colEl) => { total += Number($(colEl).val() || $(colEl).text())})
    total = total.toFixed(2);
    $(totalRowEl).val(total);
  })
}

calculateTax = () => {
  target = $(event.target)
  value = target.val();
  perUserAmount = (Number(value) / shareUserCount).toFixed(2);
  fieldClass = target[0].id == 'taxAmount' ? '.shared-tax-amount' : '.shared-tip-amount'
  $(fieldClass).text(perUserAmount);
  calculateTotals();
}

$('#add-tax-modal').on('show.bs.modal', calculateTotals);
$('#taxAmount, #tipAmount').on('input', calculateTax);
$('#add-tax-modal').modal('show');

app/views/expenses/settle_up.js.erb
html = `<%= render 'settle_up'%>`
$('#settle-up .modal-content').html(html);

function removeAfterMatch(inputString, match) {
  var index = inputString.indexOf(match);
  if (index !== -1) {
      return inputString.substring(0, index);
  }
  return inputString;
}

displaySettleUpAmount = () => {
  selectElement = event.target
  var selectedOption = selectElement.options[selectElement.selectedIndex];
  var selectedOptionName = selectedOption.textContent;
  var settle_amount = selectedOptionName.replace ( /[^\d.]/g, '' );
  document.getElementById('display_user_name').innerText = removeAfterMatch(selectedOptionName, '(Settle Amount:');
  document.getElementById('settle-amount').value = settle_amount
  $("#settle-amount").attr('readonly', 'readonly');
};


$('#settle_to_id').on('change', displaySettleUpAmount);
$('#settle-up').modal('show')

app/views/expenses/update.js.erb
$('#add-tax-modal').modal('hide');
window.location.reload();

app/views/layouts/_header_layout.html.slim
= csrf_meta_tags
= csp_meta_tag
= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"
script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"

app/views/layouts/_jgrowl_notifications.html.slim
- if flash[:notice].present?
  javascript:
    $.jGrowl("#{flash[:notice]}", { theme: 'success'})
- if flash[:alert].present?
  javascript:
    $.jGrowl("#{flash[:alert]}", {theme: 'error'})

app/views/layouts/_top_nav_bar.html.slim
header
  nav.navbar.navbar-expand-md.navbar-dark.fixed-top.bg-dark
    .container-fluid
      a.navbar-brand href="#{root_path}"  Splitwise
      button.navbar-toggler aria-controls="navbarCollapse" aria-expanded="false" aria-label=("Toggle navigation") data-bs-target="#navbarCollapse" data-bs-toggle="collapse" type="button"
        span.navbar-toggler-icon
      .d-flex
        #navbarNavDarkDropdown.collapse.navbar-collapse
          ul.navbar-nav
            li.nav-item.dropdown
              a#navbarDarkDropdownMenuLink.nav-link.dropdown-toggle aria-expanded="false" data-bs-toggle="dropdown" href="#" role="button"
                | Account
              ul.dropdown-menu.dropdown-menu-dark aria-labelledby="navbarDarkDropdownMenuLink"
                li
                  = link_to destroy_user_session_path, method: :delete, class: 'dropdown-item'
                    .icon-logout.font-size-20.mr-4
                    | Logout

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | BE Assignment Junior
    = render 'layouts/header_layout'
  - if ['sessions' , 'registrations'].include?(controller_name)
    body.text-center
      main.form-signin
        = yield
  - else
    body.d-flex.flex-column.h-100
      = render 'layouts/top_nav_bar'
    main.flex-shrink-0
      .container
        = yield

= render 'layouts/jgrowl_notifications'